---
- hosts: pi
  become: true
  gather_facts: false

  vars_files:
    - config.yml

  handlers:
    - name: reboot_pi
      reboot:

  tasks:
    - include_tasks: tasks/uvc-gadget.yml
    - include_tasks: tasks/boot-config.yml
    - include_tasks: tasks/piwebcam.yml
